### PR TITLE
Naheem lidar tutorial

### PR DESCRIPTION
**Pull request by Surfix**

### CODE REVIEW

**Comment by scottyhq** [comment]
thanks @Surfix please add an entry to this notebook in the table of contents, here is a link to edit that file on your branch https://github.com/Surfix/website2022/edit/naheem_lidar_tutorial/book/_toc.yml

**Review by scottyhq — CHANGES_REQUESTED** [review]
thanks @Surfix please add an entry to this notebook in the table of contents, here is a link to edit that file on your branch https://github.com/Surfix/website2022/edit/naheem_lidar_tutorial/book/_toc.yml

also see the "quality control" spellcheck workflow, picking up a small typo

**Comment by Surfix** [comment]
@scottyhq I have modified the notebook files as required. let me know if there is anything else to modify. 
Thanks.

**Comment by scottyhq** [comment]
@Surfix we need to put the data someplace everyone can access it  (`Cameron_Winter_DEM.tif` `cam_100_points_buffer.gpkg`) are these files small enough for you to upload in a separate github repository?

**Review by jomey — APPROVED** [review]

**Comment by scottyhq** [comment]
This looks fantastic! Let's merge now, but not that the jupyterbook output formatting for some cells could be improved with metadata tags like `hide-output` or `remove-output` https://jupyterbook.org/en/stable/content/metadata.html

Screen Shot 2022-07-05 at 10 43 13 AM

**Review by scottyhq — APPROVED** [review]

**Pull request merged**
