### PR TITLE
add modeling tutorial notebooks

### PR DESCRIPTION
**Pull request by mlwrzesien**
First draft of notebooks for modeling tutorial using LIS-SnowModel output and non-SnowEx data from SNOTEL and SNODAS.

Currently data doesn't seem to be accessible on the SnowEx JupyterHub. The bucket should have read access for the AWS role that Scott provided, but it's not currently working. I will reach out to Scott and Aaron Skolnik at NASA GSFC to see what I need to do to get the data open and accessible.

### CODE REVIEW

**Review by scottyhq — CHANGES_REQUESTED** [review]
thanks @mlwrzesien ! we'll get the S3 access sorted soon. In the meantime, you'll want to link to these notebooks in the table of contents: 

https://github.com/snowex-hackweek/website2022/blob/29fc416ec7a24d5d602b0773ed0706b02cf76afe/book/_toc.yml#L34-L38 

And also don't forget to 'restart kernel and clear all outputs' (we want notebooks empty of outputs in this repository).

**Comment by mlwrzesien** [comment]
@scottyhq - sorry for the delay, but I just made those changes. I also made an index.md page for the modeling tutorial to be a starting page for the two notebooks

**Comment by mlwrzesien** [comment]
@scottyhq I think this is the final version of the modeling notebook. I see that it's failing the checks, but I'm not sure what I need to fix to resolve everything.

**Comment by JessicaS11** [comment]
@scottyhq, any idea why the spellcheck is catching "te" in the code cells and causing an error? I would think that code inputs (here an argument name in a function definition) don't have to be "real" words?

**Comment by scottyhq** [comment]
> why the spellcheck is catching "te" in the code cells and causing an error? I would think that code inputs (here an argument name in a function definition) don't have to be "real" words? 

not sure, codespell definitely still misses a lot and has some false positives! but it's easy to add to the ignored words list: https://github.com/snowex-hackweek/website2022/blob/4ae619ebc5c504c2d492b7fd9dcbb4e76b695352/.github/workflows/qaqc.yaml#L36

**Comment by scottyhq** [comment]
@mlwrzesien these notebooks and visualizations look great! The GitHub Actions CI checks *do not* have access to `s3://eis-dh-hydro` (thus the failing checks) so I think I will just commit rendered notebooks here and exclude them from executing in CI...

**Comment by mlwrzesien** [comment]
That sounds great, thanks @scottyhq! I appreciate your help with my tutorial, especially figuring out the data access!

**Comment by scottyhq** [comment]
hmm, i can't seem to find a way to copy rendered HTML pages over to jupyterbook, and the rendered notebooks are quite big with all the visualizations. So I'm going to directly commit the rendered HTML to the `gh-pages` branch and commit empty notebooks here. cc @jomey 

```
jovyan@jupyter-scottyhq: website2022$ ls -lh book/_build/html/tutorials/modeling/
total 23M
-rw-r--r-- 1 jovyan jovyan  15M Jul  6 18:01 1_snowmodeling_tutorial.html
-rw-r--r-- 1 jovyan jovyan 8.0M Jul  6 18:01 2_snowmodeling_extra.html
-rw-r--r-- 1 jovyan jovyan  24K Jul  6 18:01 index.html

jovyan@jupyter-scottyhq: website2022$ ls -lh book/tutorials/modeling/*ipynb
-rw-r--r-- 1 jovyan jovyan 22M Jul  6 17:41 book/tutorials/modeling/1_snowmodeling_tutorial.ipynb
-rw-r--r-- 1 jovyan jovyan 16M Jul  6 17:40 book/tutorials/modeling/2_snowmodeling_extra.ipynb
```

**Review by scottyhq — APPROVED** [review]

**Comment by scottyhq** [comment]
That worked but I'm worried it will be overwritten when merging future pull requests with the empty notebooks: https://snowex.hackweek.io/tutorials/modeling/1_snowmodeling_tutorial.html 

Process on jupyterhub: 

1. run all cells
1. jb build book
1. cp -r _build/tutorials/modeling ~/modeling-rendered
1. git checkout gh-pages
1. cp -r ~/modeling-rendered/* tutorials/modeling/ 
1. git commit -a -m "rendered modeling notebooks"
2. git push

**Comment by mlwrzesien** [comment]
@scottyhq - is it too late to make a few additional changes to the notebook? Just minor text updates. To do that, is it best to create a new branch and a new PR?

**Comment by scottyhq** [comment]
not too late, yes, just start a new branch off the most recent 'main' (git checkout main, git pull, git checkout -b modeling2)

**Pull request merged**
