### PR TITLE
Swesarr

### PR DESCRIPTION
**Pull request by drboyd**
porting last year's notebook to main. thanks for the help

### CODE REVIEW

**Comment by drboyd** [comment]
quality control seems to be assigning spell errors where there aren't any. also seems to be failing because I didn't clear the kernel output before pushing .... but i did do that?

**Comment by jomey** [comment]
Looks like you do have output in your notebook:
https://github.com/snowex-hackweek/website2022/blob/bc2a76e9783768a9c44f4d2df96fce0f13209223/book/tutorials/microwave/swesarr/swesarr_tut.ipynb

Did you 'save' the notebook after you restarted and cleared all outputs?
It's two step process, which can be forgotten

**Comment by drboyd** [comment]
> Looks like you do have output in your notebook: https://github.com/snowex-hackweek/website2022/blob/bc2a76e9783768a9c44f4d2df96fce0f13209223/book/tutorials/microwave/swesarr/swesarr_tut.ipynb
> 
> Did you 'save' the notebook after you restarted and cleared all outputs? It's two step process, which can be forgotten

Ah, thanks Jo. Not sure how that happened. It's saved as cleared on my side. I apologize.

**Comment by drboyd** [comment]
Hi @jomey @scottyhq 
If I'm reading the error log for _Test / Build and test on OS - ubuntu-latest (pull_request_target)_ right, is it saying that rendering a table is no longer compatible with the hackweek websites?

> Exception occurred:
  File "/usr/share/miniconda3/envs/hackweek/lib/python3.10/site-packages/myst_parser/docutils_renderer.py", line 730, in render_table
    assert token.children and len(token.children) > 1
AssertionError

At a glance, it looks like some function `render_table()` in the hackweek library doesn't like one of the tables I've used... Which is likely either xarray or pandas. It still renders on JupyterLab though.

I can try commenting out the code blocks that render any tables. Students can uncomment those blocks during the hackweek painlessly. That's my best hunch for quickly fixing this since it doesn't seem like it's our fault.

**Comment by scottyhq** [comment]
Sees like this issue. https://github.com/executablebooks/jupyter-book/issues/1525. Likely fixed by newer jupyterbook0.13+dependencies. For the time being I just removed the markdown tables in favor of bold font

**Review by scottyhq — APPROVED** [review]

**Pull request merged**
