### PR TITLE
Tutorial - Lidar data - Try alternative download

### PR DESCRIPTION
**Pull request by jomey**
Try to use a github release of the 'tutorial-data' repo in hope of
faster data download.

### CODE REVIEW

**Comment by scottyhq** [comment]
@jomey is it faster? You can also add this unzipped dataset to `~/shared/jovyan` on the jupyterhub

**Comment by jomey** [comment]
So this build was 9 mins for the 'ubuntu-latest' and PR #78 was 11 mins.
Hard to say specifics since the download happens in a notebook cell.

**Comment by jomey** [comment]
And actually this one passed on OS X versus a failure on the above linked PR
https://github.com/snowex-hackweek/website2022/runs/7203377868?check_suite_focus=true#step%3A4%3A887=

**Review by scottyhq — APPROVED** [review]
okay, fine by me! 
cc @Surfix note this small change in path

**Pull request merged**
