### PR TITLE
Uavsar Notebook Skeleton

### PR DESCRIPTION
**Pull request by ZachHoppinen**
Started working on the uavsar tutorial, uploaded images, changed environment file to include pytools.

### CODE REVIEW

**Review by scottyhq — CHANGES_REQUESTED** [review]
thanks @ZachKeskinen @jacktarricone you'll need to add an entry in the table of contents to the notebooks you want rendered on the website: https://github.com/snowex-hackweek/website2022/edit/jack_uavsar/book/_toc.yml

**Comment by ZachHoppinen** [comment]
Thanks for that Scott. I think that should be corrected

**Comment by scottyhq** [comment]
Thanks. we'll have to add python packages in the notebooks to our existing environment definition (). I'll start a separate pull request for that. https://github.com/snowex-hackweek/website2022/tree/main/conda

**Comment by ZachHoppinen** [comment]
It is still failing to import contextily?

**Comment by scottyhq** [comment]
> It is still failing to import contextily? 

hmmm... i'm surprised by that. can you try merging the latest 'main' branch into this?

**Comment by ZachHoppinen** [comment]
Alright, pulled from the upstream/main and I have contextily in the environment.yml file but it is still failing on those imports?

**Comment by scottyhq** [comment]
> Alright, pulled from the upstream/main and I have contextily in the environment.yml file but it is still failing on those imports?

You have the latest environment now after merging 'main'. I'm seeing other errors now in the log: `RasterioIOError: /Users/zachkeskinen/Documents/uavsar_tutorial/cor.tif: No such file or directory`

**Comment by scottyhq** [comment]
FYI If you're planning to use the same dataset from 2021 on Zenodo, I've since learned you can use this python library to retrieve files from Zenodo https://www.fatiando.org/pooch/latest/api/generated/pooch.DOIDownloader.html?highlight=zenodo

**Comment by ZachHoppinen** [comment]
Perfect, I think I am gonna upload a new dataset to zenodo, but that looks like a great resource to pull it down with. Thanks for all your help Scott!

**Comment by ZachHoppinen** [comment]
Should this be confirmed and merged or should I just keep pushing to this PR as I make more changes? @scottyhq

**Comment by ZachHoppinen** [comment]
superseded by #63

**Pull request closed without merging**
