### PR TITLE
Upgraded snowexsql for new db

### PR DESCRIPTION
**Pull request by micahjohnson150**
Looking to update snowexsql to v0.3.0

### CODE REVIEW

**Comment by micahjohnson150** [comment]
@scottyhq  I attempted to update the lock file but I am getting an error running the script. This is what I see below when running it:

```
lock-environment.sh: 11: [[: not found
lock-environment.sh: 5: /home/micah/miniconda3/envs/hackweek/etc/conda/deactivate.d/geotiff-deactivate.sh: [[: not found
lock-environment.sh: 5: /home/micah/miniconda3/envs/hackweek/etc/conda/deactivate.d/gdal-deactivate.sh: [[: not found
lock-environment.sh: 11: /home/micah/miniconda3/envs/hackweek/etc/conda/deactivate.d/gdal-deactivate.sh: [[: not found

EnvironmentNameNotFound: Could not find conda environment: CondaLock
You can list all discoverable environments with `conda info --envs`.


lock-environment.sh: 19: [[: not found
lock-environment.sh: 27: conda-lock: not found
Generate environment.yml for BinderHub 
lock-environment.sh: 32: conda-lock: not found
lock-environment.sh: 46: [[: not found
```

Are you seeing this on your end?

**Comment by scottyhq** [comment]
> Are you seeing this on your end? 

strange. seems like some sort of shell error. If you run on the jupyterhub it should work

**Comment by micahjohnson150** [comment]
Ok I was able to run it. It was a mistake on my end. Turns I was being sloppy in following instructions. `sh lock-environment.sh` produces an error. `./lock-environment.sh` actually changes things.  

Next question. In snowexsql I only changed the source code, should I expect the lock to have changed all that it did?

**Comment by jomey** [comment]
The installation of the snowexsql is via a workaround that executes pip after the environment is set up. The changes you are seeing are packages that got updated since the last time the environment resolved the dependencies and we haven’t specified a specific version for those.

**Review by jomey — APPROVED** [review]

**Comment by micahjohnson150** [comment]
Do we think the MacOS failure here is a show stopper? I am not sure I understand whats failing here.

**Comment by jomey** [comment]
> Do we think the MacOS failure here is a show stopper? I am not sure I understand whats failing here.

Seems like an unrelated error with the OOP tutorial that is not using the snowexsql package. Go ahead and merge

**Comment by micahjohnson150** [comment]
That's what I am talking about! All aboard! :steam_locomotive:

**Pull request merged**
