### PR TITLE
Application form

### PR DESCRIPTION
**Pull request by aaarendt**

### CODE REVIEW

**Comment by scottyhq** [comment]
One thing we discussed is *requiring* a GitHub ID right off the bat?
```
If you have a GitHub account, please share your username
(if you do not yet have a GitHub account, don't worry, we will guide you through that process soon!)
```

GitHub Username
All project teams will use GitHub to collaborate and work together on their code. If you do not already have a username, please sign up for a free account: https://github.com

**Comment by scottyhq** [comment]
> These three questions will be reviewed by our organizing committee in some detail. Participant selection will be made with the goal of enhancing the diversity of our communities and building lasting connections that foster open science and data sharing. 

I think we should update this sentence on the google form to match the new 'Selection Considerations' which looks great!

**Comment by aaarendt** [comment]
> One thing we discussed is _requiring_ a GitHub ID right off the bat?
> 
> ```
> If you have a GitHub account, please share your username
> (if you do not yet have a GitHub account, don't worry, we will guide you through that process soon!)
> ```
> 
> GitHub Username All project teams will use GitHub to collaborate and work together on their code. If you do not already have a username, please sign up for a free account: https://github.com

Thanks for flagging this - I'm on a call with Jane and we decided it's better to require this at the stage of the registration form, instead the application (since we get over-subscribed). So we deleted that question in the application form so that we're not asking it twice.

**Review by scottyhq — APPROVED** [review]
sounds good!

**Pull request merged**
